language: node_js
node_js:
  - "22.x"
  - "lts/*"
  - "node"

os:
  - linux
  - windows
  - osx

branches:
  only:
    - main
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

script:
  - npm run lint
  - npm test
  - npm run test:coverage

after_success:
  - npm run coverage

notifications:
  email: false
  webhooks: false
  